### ISSUE TITLE
Add autoPull as option in Docker Wizard and POM [enhancement]

### ISSUE THREAD

**Issue by jmhenley5326** [TIBCOSoftware/bw6-plugin-maven#105]
I would like to see an autoPull option added to the Docker features.

Next to the "Image Name" field have a check box for autoPull. This will add the <autoPull> tag to the plugin configuration.

<configuration>
          <skip>false</skip>
          <dockerHost>${bwdocker.host}</dockerHost>
          <certPath>${bwdocker.certPath}</certPath>
          <autoPull>...</autoPull>

This is especially useful when pulling from external repos to ensure you have the latest base image. Especially useful for development environments.

**Comment by SonaliDasgupta** [comment]
Hi @jmhenley5326 . To clarify about this feature, I understand that we need an autoPull option , which when selected, pulls the latest version of the docker image specified in 'Image Name'. This shall be used during docker start or docker run goal, to pull the latest version of the docker image from a remote repository if not found locally. Is this the expected behavior ? Also, is this behavior required for only the BWCE Base Image, or all the docker images being built ?

**Comment by jmhenley5326** [comment]
This is the expected behavior yes.
As for all the docker images, that is difficult to answer. I would think it would apply to whatever the FROM image is set to. 

    On Tuesday, August 21, 2018 5:07 AM, Sonali Dasgupta <notifications@github.com> wrote:
 

 Hi @jmhenley5326 . To clarify about this feature, I understand that we need an autoPull option , which when selected, pulls the latest version of the docker image specified in 'Image Name'. This shall be used during docker start or docker run goal, to pull the latest version of the docker image from a remote repository if not found locally. Is this the expected behavior ? Also, is this behavior required for only the BWCE Base Image, or all the docker images being built ?—

**Comment by SonaliDasgupta** [comment]
Enhancement has been added for release 2.1.0 .
