### ISSUE TITLE
How to reference artifacts hosted by Maven repository

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#125]
Hi,

bw maven plugin does generate a parent eclipse project which contains a pom.xml with relative path to the other modules representing the dependencies.

With the fact that my pipeline does publish build artefacts to a maven repository, say hosted by nexus, artifactory or vsts , how can we have the pom.xml referencing an external maven repository which does have the dependencies needed. 

Thanks,

**Comment by ashutoshbhide** [comment]
Hi @mshahat 

Right now the SharedModules can be referred from the Maven Repo.

The Application and AppModule project still needs to be at source because thats what you are building. We need to understand the use-case where the Application and AppModule also needs to be downloaded from Maven Repo.

-Ashutosh

**Comment by mshahat** [comment]
Hi Ashutosh, Yes it's more about SharedModules. 

Can you share the instructions on how to achieve so ? 

Thanks,

**Comment by ashutoshbhide** [comment]
Hi @mshahat 
Can you try the instructions at this page.

https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule

If you need further information do let me know. 

-Ashutosh
