### ISSUE TITLE
Can we have parent project gone

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#127]
Hi, 

Parent project is an extra module that has to be commit to source code control and maintained with the module in scope. Is there a plan to get rid of the parent project and include the pom.xml with the module in scope ? 

Thanks,

**Comment by ashutoshbhide** [comment]
Hi @mshahat 

No that is a Maven limitation. In Maven the aggregating project always needs to have the packaging type as POM and cant generate any build artifacts. 
Since we have to build at-least Application and AppModule project ( now the SharedModules can be directly referred from the Maven Repo) so the parent project is required.

Again its Maven way of doing things. The JEE application also usually have a Parent project.

Ashutosh

**Comment by mshahat** [comment]
Thanks @ashutoshbhide  , closing this.
