### ISSUE TITLE
Not working "mvn -s c:\temp\settings.xml install" when the proyect have libraryes

### ISSUE THREAD

**Issue by ljferrero** [TIBCOSoftware/bw6-plugin-maven#148]
Maven Plugin version: 1.3.1

Maven version: 3.3.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version: BWCE 2.3.4

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Create project HelloWorld with Business Studio in Windows 10
2. Configure project HelloWorld.module to  "Convert Java Project"
3. Add a YYYYY.jar file (anyone) to the lib folder 
4. Apply the plugin to project HelloWorld in Business Studio (Generate POM for Application)
5. Configure settings.xml file with a local repository new, never with the of by defect.
Example:
	...<localRepository>C:/Users/XXXXX/.m2/repo</localRepository>....

Also you shoud change the path of settings.xml
Example:
	C:\Users\XXXXX\.m2\temp\settings.xml
6. Execute command -> mvn -s C:\Users\XXXXX\.m2\temp\settings.xml install
7. The plugin install the library YYYYY.jar in of  the repository by  default (C:/Users/XXXXX/.m2/repository/tempbw) and should be in C:/Users/XXXXX/.m2/repo/tempbw

**Additional environment details if any:**
OS Windows 10

**Describe the results you received:**
C:\datos\GIT_REPO\HelloSantander\HelloSantander.parent>mvn -s C:\Users\n90468\.m2\temp\settings.xml install
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
C:\Users\n90468>mvn install:install-file  -Dfile="C:\datos\GIT_REPO\HelloSantander\HelloSantander.module\lib\YYYYY.jar" -DgroupId=tempbw -DartifactId=YYYYYY -Dversion=0.0.0 -Dpackaging=jar
[INFO] Scanning for projects...
[INFO].........

**Describe the results you expected:**
The trace of log should be:
....
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
C:\Users\n90468>mvn -s C:\Users\n90468\.m2\temp\settings.xml install:install-file  -Dfile="C:\datos\GIT_REPO\HelloSantander\HelloSantander.module\lib\YYYYY.jar" -DgroupId=tempbw -DartifactId=YYYYYY -Dversion=0.0.0 -Dpackaging=jar
......

and the YYYYY.jar file should be in C:/Users/XXXXX/.m2/repo/tempbw

**Comment by ankitapandey1** [comment]
Hi ljferrero ,

Since Maven Compiler could not Load JAR files from classpath in the project , so we temporarily add all the JARs from classpath as a Maven artifact in the local repository under the group name "tempbw" ,JAR name as aritfact id the and version as "0.0.0" and add this programatically as a dependency in the maven model.

Now Maven compiler can compile the source with this JAR as a dependency.
Once the lifecyle completed we remove this dependency from .m2 repository .

You can refer to the following source to find out how we do it.
1. MvnInstallExecutor.java
2. BWProjectLifeCycleListener.java**
