### ISSUE TITLE
FABRIC8 - KUBERNETES ENV VARIABLES

### ISSUE THREAD

**Issue by loreCande81** [TIBCOSoftware/bw6-plugin-maven#196]
Hi,
I set the following env variables:

KUBERNETES_MASTER=xxx
KUBERNETES_NAMESPACE=default
KUBERNETES_CERTS_CA_FILE=xxx
KUBERNETES_TRUST_CERTIFICATES=true

but when I launched the fabric8:apply goal it is failing because is not able to find a valid KUB instance.
Of course the xxx have been replaced with my specific IP and paths. Is there any other variable I should define. I am using the google cloud kub service.
Thanks

**Comment by SonaliDasgupta** [comment]
Hi @loreCande81 , this issue seems to be because the Fabric8 plugin cannot find a Kubernetes Deployment or Service. Please add the following environment variable : APP_CONFIG_PROFILE=docker. 

In version 2.0.1 of the BW6 Maven plugin, there has been an upgrade of the Fabric8 Maven plugin. A few steps in deploying the applications to Kubernetes have been updated. The 'fabric8:json' goal will no longer work with the new version of Fabric8 plugin (Fabric8 3.x). 

If your version of the BW6 maven plugin is version 2.0.1 , the goals to be executed sequentially for deployment to Kubernetes are as follows :
1.   com.tibco.plugins:bw6-maven-plugin:bwfabric8json
2.   initialize fabric8:resource
3.   initialize fabric8:apply

If your version of BW6 Maven plugin is older than version 2.0.1, the goals to be executed are:
1. initialize fabric8:json
2. initialize fabric8:apply

Please refer to https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Building-applications-for-TIBCO-BusinessWorks-Container-Edition-in-Docker-and-Kubernetes-or--Openshift for details.

If the issue persists after adding the environment variable and following the above steps, could you please share your project / POM files and the error stack trace?

**Comment by SonaliDasgupta** [comment]
Closing the question. Please reopen in case of any query.

**Comment by loreCande81** [comment]
[workspace.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2518931/workspace.zip)
I attached the project as whqt you proposed didnt work. I am using an older version than  2.0.1 of the plugin. the goal initialize fabric8:json works, but not the initialize fabric8:apply. The error I am getting is the following: NO Kubernetes instance found.
