### ISSUE TITLE
Enhacement: validation of maven properties bwHome and tibcoHome

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#256]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.1.1 

Maven version: 3.5.3

Product : Either of TIBCO ActiveMatrix Businessworks 6

Product version: 6.5.1

Component: Maven build plugin

**Steps to reproduce the issue:**
1. If you put the tibcoHome to your current tibcoHome (like C:/tibco/bw6
2. And then set bwHome to . 
3. It's going to pass validation but it's going to be stuck at Starting BW Engine to Test Mode.

We should enhance validation to avoid this issue and get a bad developer experience. We should check that the bwHome is pointing to the right directory and all executables are going to be found.

**Comment by alexandrev** [comment]
Also when this happen no error is shown in Studio console, so this could be another improvement, try to redirect standard error to the console so at least if something is not able to launch the java command you get noticed.

**Comment by SujataDarekar** [comment]
@alexandrev With the latest version if you check when we provide the incorrect Tibco home / bw home, we are showing log message as "Provided TibcoHome directory is invalid. Skipping Test Phase" on console and in this case, BW engine doesn't get starts since the tibco/bw home is invalid. and I think this should be fine. Please let us know if you think different

**Comment by SujataDarekar** [comment]
@alexandrev  Closing the issue since the validation is already present
