### ISSUE TITLE
Plugin goals usage

### ISSUE THREAD

**Issue by Strickmabil** [TIBCOSoftware/bw6-plugin-maven#277]
Maven Plugin version: 2.1.1

Maven version: 3.2

Product : TIBCO ActiveMatrix Businessworks 6

Product version:

Component: Maven build plugin

Is there any way to get details on the usage of these goals? Since wiki Help page is out-of-date.

[ERROR] Could not find goal 'bwtesf' in plugin com.tibco.plugins:bw6-maven-plugin:2.1.1 among available goals bwdeployer, bwear, bwfabric8json, bwinstall, bwmodule, bwreport, bwtes
t, bwtestear, bwtestmodule -> [Help 1]

**Comment by awagle** [comment]
This is a typo. bwtest is the right goal. bwdeployer, bwear, bwfabric8json, bwinstall, bwmodule, bwreport, bwtes
t, bwtestear, bwtestmodule are the available goals as reported in the error. Please have a look at the wiki again -https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki. Rather than listing every goal, the wiki is designed around features and then the required goal for each feature.
