### ISSUE TITLE
bw6.4.2 shared plugin and maven

### ISSUE THREAD

**Issue by adamholtmart** [TIBCOSoftware/bw6-plugin-maven#407]
Maven Plugin version: 1.3.1

Maven version: 3.6.3

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition
TIBCO BUSINESSWORKS 6.4.2
Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin
Maven Eclipse Plugin

**Steps to reproduce the issue:**
1.  I define the StringEditor shared plugin in the application pom
2.  I run the maven build
3.  The StringEditor is not imported.   Worked with Hitesh on a call today.  

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
[tibcosharedplugin.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4140868/tibcosharedplugin.zip)

**Comment by SujataDarekar** [comment]
@adamholtmart After adding the java plugin dependency,  does the plugin get added in generated EAR file? Like Shared module it will not get imported in studio workspace but it should get added in the EAR file.

**Comment by HiteshNembhwani** [comment]
[SampleProject.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4441524/SampleProject.zip)
@adamholtmart - attached sample projects here for quick reference.

**Comment by SujataDarekar** [comment]
@adamholtmart  Below are the ways to add Java plugin in EAR.
1. Manually pull the Java plugin in studio and add the dependency of java plugin in "Required Modules " present in dependencies tab of module.
2. Regenerate the POM for the BW application if it is already generated.
3. Run the package goal. It will include the dependent Java module in EAR.
This is one of the ways of packaging shared module in application EAR.
I have attached testshareplugin1.zip for your details

Another way of doing this is
1. I assume that the java plugin is already present in m2 repository
2. Add the dependency of Java plugin in BW project and run the package goal . In case of shared module after adding the dependency of installed shared module, it will import in workspace but this will not happen in case Java Plugin because we provide that support to only shared module.
3. When you run the package goal ,it will package the dependent modules. Please refer the testshareplugin2.zip for more details.

Drive Link for sample Project:
https://drive.google.com/drive/folders/12E5Dgv9GHCdQTDERJzpBmvKDEitCysnM?usp=sharing
