### ISSUE TITLE
TIBCO BWCE Maven Plugin not able to create Host Volumes

### ISSUE THREAD

**Issue by pavanij24** [TIBCOSoftware/bw6-plugin-maven#469]
Hi Team,

We are using the TIBCO Maven plugin for CICD implementation in our project.
We are facing issue with implementing the “Host Volume” using the maven plugin which is working with “docker run” command.
I have gone through the References for FABRIC8 and Docker Maven plugin section but couldn’t fix the issue.
Please help to suggest

Below are the reference of Host properties:
![image](https://user-images.githubusercontent.com/67406037/85864738-8c25c980-b7e2-11ea-8493-aab647853038.png)

POM.xml
![image](https://user-images.githubusercontent.com/67406037/85661812-c6a14080-b6d4-11ea-824b-fe0c4b7ee20b.png)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
-->
Maven Plugin version: 2.6

Product :  TIBCO Businessworks Container edition

Product version: 2.5.1

Component: Maven Eclipse Plugin

**Comment by awagle** [comment]
What are the maven goals being run. Are you running mvn docker:create-volume. Please look at https://github.com/fabric8io/docker-maven-plugin documentation for available goals. This will not automatically be done by the goals listed in the wiki page. Please attach a sample projects so that we can reproduce it. Please reopen if this issue is not resolved by the above goal.
