### ISSUE TITLE
Running BW Application from the studio modifies the Bundle ClassPath

### ISSUE THREAD

**Issue by maulikdoshi82** [TIBCOSoftware/bw6-plugin-maven#476]
When a BW Maven project is run from inside the studio (As a BusinessWork Application) - Studio adds a full PATH as it's part of Class Path (MANIFEST.MF). This eventually needs to be removed while deploying on docker otherwise container breaks due to local M2 references.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.6.0.001

Maven version: 3.6.1

Product : TIBCO Businessworks Container edition

Product version: 2.5.3 V26 2020-05-15

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Unzip both the folders attached herwith inside a single folder. 
2. Import common first and then sample project.
2. Verify tibco.bwce.sample.palette.jms.Basic\META-INF\MANIFEST.MF is referring to Bundle-Classpath : .
3. Run the sample project. Verify the Bundle-Classpath. It has loaded up all .m2 packages and other path in it's classpath. 

**Additional environment details if any:** RedHat Linux

**Describe the results you received:** It has loaded up all .m2 packages and other path in it's classpath. 

**Describe the results you expected:**It should not modify Bundle-Classpath

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vpawar-ai** [comment]
Hi @maulikdoshi82, Did you convert your BW application module to Java project (Using right-click, Configure->Convert to Java Project)? Could you please share the project?

**Comment by maulikdoshi82** [comment]
[sample.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4928408/sample.zip)

Apologies for the delay. Had to reduce it quite a much. Sample project depends on common module. Both are maven projects.
[hubble-tibco-bwce-common-module.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4928477/hubble-tibco-bwce-common-module.zip)

**Comment by vpawar-ai** [comment]
Hi @maulikdoshi82,

Thanks for sharing the code. I couldn't use it to reproduce the issue because it had other required dependencies(hubble-common-model) which were missing.

However, I see custom java code in your shared module which is referring to couple of jars from lib folder as well as some dependencies in pom.xml. Could you compare the list of jars in Bundle-Classpath against the jars from shared module?
I see BW6 maven plugin 2.3.1 is being used. Could you also try using latest version 2.7.0? 

It will be great if you can share a sample project without additional dependencies & detailed steps to help reproduce the issue.

Thanks.

**Comment by awagle** [comment]
This is expected behavior. The runtime engine is OSGI and bundle classpath is local and cannot reference jars outside the bundle while debugging and running in Studio. Hence the maven plugin modifies the bundle classpath so that debugger can load the right jar files. This only happens if you have jars referenced using pom.xml

However when the Ear is generated bundle classpath should be reverted to original. Please try with 2.7 as Vishal suggested and share the project and generated EAR file so that we can double check if there is a bug.

**Comment by maulikdoshi82** [comment]
We use build ear via maven goals and still see it being there. Will try with 2.7 and update accordingly.

**Comment by maulikdoshi82** [comment]
It's not adding the path when building the ear. Closing the issue.
