### ISSUE TITLE
save root pom on svn

### ISSUE THREAD

**Issue by dabbate** [TIBCOSoftware/bw6-plugin-maven#8]
Hello,
I'm working with BW 6.3.1. I've mavenized my BW application. I need to save my BW application on SVN repository using BusinessStudio. 
I don't know how to save the root pom, generated by default inside the workspace, because is not visible from the Business Studio Project Explorer.
In the image attached I circled in red the pom file visible in the file system and not visible in the Project Explorer.
![fig1](https://cloud.githubusercontent.com/assets/17925787/13875687/9a4695f6-ecff-11e5-85e3-63f1e12f035d.JPG)

How can I save on SVN the root pom using Business Studio?

Best regards,
Danilo

**Comment by artificialintellect** [comment]
I worked around this by doing some manual steps

1. Create a new General Project and copy the parent POM into it
2. Check the general project as [svn-root]\project
3. Check in the two bw projects (application and module) as [svn-root]\project\application and [svn-root]\project\module
4. Delete the application and module
5. Check everything back out from [svn-root]\project (recommend using Checkout as Maven Project)

After step 5 you should have three projects checked out - the multi-module project and the two bw projects (application and module).  You can just close the multi-module level project since you generally only need to change that when you want to make a release (to set the version number)

As extra credit I ended up creating a maven archetype that would create the proper structure up front and that is how I create my mavenized tibco projects now.

**Comment by ashutoshbhide** [comment]
Now the root POM will be generated in a seperate folder at the same level as Application project. 
Now it can be added to SVN without the workaround
