### ISSUE TITLE
BW6.3 Maven Plugin for OSX

### ISSUE THREAD

**Issue by dabbate** [TIBCOSoftware/bw6-plugin-maven#9]
Hi,
I'm trying to install BW6.3 on OSX but fails. Reading the README (https://github.com/TIBCOSoftware/bw6-plugin-maven) I can't find anything related to OSX. Can you confirm whether Maven Plugin is available for OSX?

Below log of "install.sh":
mbpdanabb:TIB_BW_Maven_Plugin_1.0.0 $ ./install.sh 

Starting Plugin Code for Apache Maven and TIBCO BusinessWorks™ installation ....  

Buildfile: /Users/dabbate/Downloads/TIBCO/BW/6.3/Maven/TIB_BW_Maven_Plugin_1.0.0/build.xml

BUILD FAILED

" does not exist in the project "main". 

Total time: 0 seconds

**Comment by mhale** [comment]
Hi dabbate,

This fails because the install.sh file originally had Windows line endings. It's been fixed in the updated installer, but you can also fix it yourself by changing the line endings in install.sh.

There is also an issue on OSX around the generated properties filenames, which I have submitted a PR for. The workaround for now is to rename the properties files manually.

**Comment by dabbate** [comment]
Hi Mark, 
Just tried on my Mac downloading the updated installer, and it works correctly. You can close this issue.

Thanks,
Danilo

**Comment by roagarwal** [comment]
Issue is closed.
