### ISSUE TITLE
Remove "parent" part from shared modules pom

### ISSUE THREAD

**Issue by John-Zg** [TIBCOSoftware/bw6-plugin-maven#98]
Hi, 
when creating the pom files, there is a "parent" part created in the pom files of the shared modules. 
This is not necessary, but even worst, it prevents that shared module to be used by other applications. 
Example:

This is created by the tibco maven plugin:
<parent>
    <groupId>com.tui.int.cyrus.bw6</groupId>
    <artifactId>SomeApplication.parent</artifactId>
    <version>2.7.0</version>
    <relativePath>..\SomeApplication</relativePath>
  </parent>

This would be the correct way and we always need to change it manually:
<groupId>com.tui.int.cyrus.bw6</groupId>
  <artifactId>someArtifactID</artifactId>
  <version>2.0.0</version>

Please change this behavior (cause it doesn't make sense), this is an official request by TUI and is already placed at Tibco Support.

**Comment by John-Zg** [comment]
Actually, you (probably) just need to remove line 43 in the ModulePOMBuilder class and add 2 lines, one to add the artifact id of the shared module and one to add a version.

**Comment by pistantan** [comment]
Hi John-Zg,

We here at Lufthansa Cargo are facing the same issue, and are considering our options, including implementing a workaround. Did you guys manage to go around this somehow? Our alternative would be to include a step where we manipulate the pom itself before running the script.

**Comment by NidhiRajeshDhoka** [comment]
Hi Zohn-Zg,

If you want a shared module to be used by multiple applications(more than one),then you need to generate pom.xml for the respective shared module independently by right clicking the shared module and selecting the option "generate POM for shared module" instead of generating the POM for the shared module by the right clicking the parent.Then installing the independent shared module into the repository and then adding its dependency into application.In such case you wont get the parent part in the shared module's pom.xml.

**Comment by SujataDarekar** [comment]
Please follow the previous comment. Closing the issue based on the last comment
